#pragma once

#define RGB_MATRIX_FRAMEBUFFER_EFFECTS
#define RGB_MATRIX_KEYPRESSES
#define TAPPING_TERM 145
#define TAPPING_TERM_PER_KEY
#define COMBO_TERM 50
#define COMBO_MUST_TAP_PER_COMBO
// #define LEADER_TIMEOUT 300
// #define LEADER_PER_KEY_TIMING
// #define ACHORDION_STREAK

